services:

  backend:
    build: ./backend
    restart: always
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend            
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "3100:80"         
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend